-- ============================================================
-- Automatic Fraud Detection - Application Database Initialization
-- ============================================================

-- Ce script initialise les tables applicatives réellement utilisées
-- par les DAGs Airflow et les modules Python du projet.
--
-- Tables principales :
-- - fraud_predictions
-- - fraud_alerts
-- - labeled_transactions
-- - model_cd_decisions
--
-- Les tables sont créées avec CREATE TABLE IF NOT EXISTS afin de ne pas
-- supprimer les données existantes.
--
-- Pour une réinitialisation complète, décommenter les DROP ci-dessous.

-- DROP TABLE IF EXISTS model_cd_decisions CASCADE;
-- DROP TABLE IF EXISTS fraud_alerts CASCADE;
-- DROP TABLE IF EXISTS fraud_predictions CASCADE;
-- DROP TABLE IF EXISTS labeled_transactions CASCADE;


-- ============================================================
-- Predictions table
-- Stores fraud prediction outputs generated by the inference DAG.
-- ============================================================

CREATE TABLE IF NOT EXISTS fraud_predictions (
    id SERIAL PRIMARY KEY,
    trans_num TEXT,
    cc_num BIGINT,
    amt DOUBLE PRECISION,
    category TEXT,
    transaction_time TIMESTAMP,
    is_fraud_predicted INTEGER,
    fraud_probability DOUBLE PRECISION,
    fraud_alert_threshold DOUBLE PRECISION,
    model_name TEXT,
    model_alias TEXT,
    predicted_at TIMESTAMP DEFAULT NOW()
);


-- ============================================================
-- Fraud alerts table
-- Stores alerts generated when a transaction is predicted as fraud.
-- One alert per transaction is allowed.
-- ============================================================

CREATE TABLE IF NOT EXISTS fraud_alerts (
    id SERIAL PRIMARY KEY,
    trans_num TEXT UNIQUE NOT NULL,
    amt DOUBLE PRECISION,
    merchant TEXT,
    category TEXT,
    city TEXT,
    state TEXT,
    transaction_time TIMESTAMP,
    fraud_probability DOUBLE PRECISION NOT NULL,
    fraud_alert_threshold DOUBLE PRECISION NOT NULL,
    model_name TEXT,
    model_alias TEXT,
    notification_channel TEXT DEFAULT 'discord',
    notification_status TEXT DEFAULT 'created',
    created_at TIMESTAMP DEFAULT NOW(),
    notified_at TIMESTAMP
);


-- ============================================================
-- Labeled transactions table
-- Stores complete labeled transactions for incremental retraining.
-- ============================================================

CREATE TABLE IF NOT EXISTS labeled_transactions (
    id SERIAL PRIMARY KEY,
    trans_num TEXT UNIQUE NOT NULL,
    cc_num BIGINT,
    merchant TEXT,
    category TEXT,
    amt DOUBLE PRECISION,
    first_name TEXT,
    last_name TEXT,
    gender TEXT,
    street TEXT,
    city TEXT,
    state TEXT,
    zip INTEGER,
    lat DOUBLE PRECISION,
    long DOUBLE PRECISION,
    city_pop INTEGER,
    job TEXT,
    dob DATE,
    merch_lat DOUBLE PRECISION,
    merch_long DOUBLE PRECISION,
    is_fraud INTEGER NOT NULL,
    transaction_time TIMESTAMP,
    received_at TIMESTAMP DEFAULT NOW(),
    integrated_in_training BOOLEAN DEFAULT FALSE,
    integrated_at TIMESTAMP
);


-- ============================================================
-- Model CD decisions table
-- Stores champion / challenger comparison and promotion decisions.
-- ============================================================

CREATE TABLE IF NOT EXISTS model_cd_decisions (
    id SERIAL PRIMARY KEY,
    model_name TEXT,
    champion_version TEXT,
    challenger_version TEXT,
    champion_average_precision DOUBLE PRECISION,
    challenger_average_precision DOUBLE PRECISION,
    champion_recall_fraud DOUBLE PRECISION,
    challenger_recall_fraud DOUBLE PRECISION,
    challenger_precision_fraud DOUBLE PRECISION,
    promoted BOOLEAN,
    decision_reason TEXT,
    decided_at TIMESTAMP DEFAULT NOW()
);


-- ============================================================
-- Standard indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_fraud_predictions_trans_num
ON fraud_predictions(trans_num);

CREATE INDEX IF NOT EXISTS idx_fraud_predictions_predicted_at
ON fraud_predictions(predicted_at);

CREATE INDEX IF NOT EXISTS idx_fraud_predictions_is_fraud_predicted
ON fraud_predictions(is_fraud_predicted);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_trans_num
ON fraud_alerts(trans_num);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_created_at
ON fraud_alerts(created_at);

CREATE INDEX IF NOT EXISTS idx_fraud_alerts_notification_status
ON fraud_alerts(notification_status);

CREATE INDEX IF NOT EXISTS idx_labeled_transactions_trans_num
ON labeled_transactions(trans_num);

CREATE INDEX IF NOT EXISTS idx_labeled_transactions_integrated
ON labeled_transactions(integrated_in_training);

CREATE INDEX IF NOT EXISTS idx_labeled_transactions_received_at
ON labeled_transactions(received_at);

CREATE INDEX IF NOT EXISTS idx_model_cd_decisions_model_name
ON model_cd_decisions(model_name);

CREATE INDEX IF NOT EXISTS idx_model_cd_decisions_decided_at
ON model_cd_decisions(decided_at);